#include <iostream>
#include <string>
#include <vector>

std ::vector<std ::string> AnimaNames = {
    "cat", "dog", "birds", "fish", "frog", "bear",
    "lion",
    "tiger",
    "elephant",
    "rabbit",
    "fox",
    "deer",
    "horse",
    "cow",
    "pig",
    "sheep",
    "goat",
    "duck",
    "penguin",
    "koala",
    "panda",
    "squirrel",
    "otter",
    "dolphin",
    "octopus",
    "kangaroo",
    "chimpanzee",
    "gorilla",
    "platypus",
    "hedgehog",
    "raccoon",
    "ostrich",
    "seahorse",
    "sloth",
    "cheetah"};
std::vector<std ::string> CarNames = {
    "Beetle",
    "Mustang",
    "Camaro",
    "Charger",
    "Wrangler",
    "Ferrari",
    "Porsche",
    "Lamborghini",
    "Corvette",
    "Raptor",
    "Gallardo",
    "Civic",
    "Impreza",
    "Challenger",
    "Bronco",
    "Cruze",
    "Focus",
    "Carrera",
    "Aventador",
    "Viper",
    "Eclipse",
    "Sierra",
    "Pathfinder",
    "Outlander",
    // "Touareg",
    // "X5",
    // "Rogue",
    // "Jetta",
    // "Sentra",
    // "Optima",
    // "Veloster",
    // "Cayenne"
};

std ::vector<std ::string> CityNames = {
    "London",
    "New York",
    "Tokyo",
    "Paris",
    "Sydney",
    "Mumbai",

    "Rio de Janeiro",
    "Dubai",
    "Barcelona",
    "Los Angeles",
    "Amsterdam",
    "Singapore",
    "Rome",
    "Seoul",
    "Berlin",
    "Toronto",
    "Buenos Aires",
    "Beijing",
    "Delhi",
    "Cape Town",
    "Moscow",
    "Bangkok",
    "Athens",
    "Stockholm",
    "Istanbul",
    "Havana",
    "Varanasi",
    "Cairo",
    "Zurich",
    // "Prague",
    // "Nairobi",
    // "Wellington",
    // "Lisbon",
    // "Helsinki",
    // "Budapest",
    // "Edinburgh",
    // "Jerusalem",
    // "Oslo",
    // "Kyoto",
    // "Dublin",
    // "Brussels",
    // "Warsaw",
    // "Santiago",
    // "Casablanca",
    // "Kuala Lumpur",
    // "Copenhagen"

};

// int main()
// {
//     std ::string str = CityName[0];

//     std ::cout << str[0];
// }
